### ISSUE TITLE
Allow saving of daylist

### ISSUE THREAD

**Issue by dvdmuckle** [dvdmuckle/spc#155]
Spotify recently added another kind of dynamically generated playlist like Discovery Weekly, called the "daylist." This refreshes at different times over the day, and it would appear a daylist is unique both to the time of day as well as the day of the week. It would be a welcome addition to be able to save the daylist, much like how one can already save the Discover Weekly playlist.

More on the daylist feature from Spotify: https://newsroom.spotify.com/2023-09-12/ever-changing-playlist-daylist-music-for-all-day/

**Comment by sathuhebbar** [comment]
Hello, does it require a premium version of Spotify for trying this feature out? I'm from India so I don't know if I can access this daylist from India with a free account. I would be happy to work on this issue if you could point me to some resource about this daylist feature. Thank you.

**Comment by dvdmuckle** [comment]
It looks like the daylist feature does not require a premium account, however I'm not sure if one can save a playlist without a premium account. Unfortunately developing on this project without premium is somewhat difficult, as many features of this project require Spotify features that are locked behind premium. That being said, from what I can see, the daylist feature and saving playlists do not require premium.

**Comment by sathuhebbar** [comment]
Cool, may I take up this task?

Also, may I ask any questions I have regarding the spc or the code here, or is there any other dedicated platform for communication?

Thank you.

**Comment by dvdmuckle** [comment]
For sure, I'll assign this issue to you!

As for communications platforms, there aren't any besides here, but I am in the Hacktoberfest Discord server if you want to reach out to me there.

**Comment by dvdmuckle** [comment]
Hey there @sathuhebbar, just wanted to check in to see how your progress is on this, do you feel confident you'll be able to get this in by the end of the month? Happy to help if you have any questions.

**Comment by PHAGUN-JAIN** [comment]
HI @dvdmuckle , I would like to try add this command, if this is still open can i take this?

**Comment by dvdmuckle** [comment]
@PHAGUN-JAIN go for it, yeah!

**Comment by PHAGUN-JAIN** [comment]
Hey thanks for assigning, I made few changes wanted to try out if they work, but while trying to build the binary locally I am facing some issues i did the following command
```
sudo make go-build
```
and following is the output

![image](https://github.com/user-attachments/assets/5c9e739a-710d-400a-86ca-159afa78856e)

can you help me out here please!

**Comment by dvdmuckle** [comment]
@PHAGUN-JAIN why are you using `sudo`? You shouldn't need to.

Lemme try to reproduce this on my side. Currently dealing with a cold so my response might be delayed.

**Comment by PHAGUN-JAIN** [comment]
i tried out without `sudo` in morning it said permission denied while trying to access some mock folder

**Comment by PHAGUN-JAIN** [comment]
I tried out again and it worked this time !!!
did `make clean`, deleted vendor folder and ran `make go-vendor` , `make go-build`  working now !!

able to use build  `./spc`

![image](https://github.com/user-attachments/assets/db5360d0-98ba-446a-bef2-57fd3761f993)

**Comment by PHAGUN-JAIN** [comment]
hey @dvdmuckle I raised a PR here [link](https://github.com/dvdmuckle/spc/pull/222) for this, you can have a look whenever you are back thanks :)

**Comment by dvdmuckle** [comment]
Closed by #222 , thank you @PHAGUN-JAIN!
