### ISSUE TITLE
Refactor release build workflow to use matrix

### ISSUE THREAD

**Issue by dvdmuckle** [dvdmuckle/spc#157]
Currently, the workflow to build and publish new releases is very repetitive, with a manually defined job for each OS and arch. It would be nice to instead have these arch/OSes defined in a matrix instead.

**Comment by giovannism20** [comment]
Are you referring to this file: .github/workflows/build-release.yml ?

**Comment by dvdmuckle** [comment]
That's the one!

**Comment by giovannism20** [comment]
I'll improve it!

**Comment by giovannism20** [comment]
I think we can also close this issue @dvdmuckle

**Comment by dvdmuckle** [comment]
Closed by #159 , thank you @giovannism20!
