### ISSUE TITLE
Allow spc switch to only config device, but don't switch playback to it

### ISSUE THREAD

**Issue by dvdmuckle** [dvdmuckle/spc#29]
The `spc switch` command can write to config the device to use for commands, switch to a device, and start playback for it, but it cannot just write to config the device to use. This should be implemented behind a flag of some kind.

**Comment by AkmalArifin** [comment]
Hey it's this issue still open, if it's I have an interest to do this issue. May i assigned to this issue?

**Comment by dvdmuckle** [comment]
Sure thing!

**Comment by dvdmuckle** [comment]
So. Reading this issue and looking at the current commands, I realized this is something already allowed. I opened this issue four years ago and must have been thinking of something else when I wrote this... I'm going to close this issue. I apologize @AkmalArifin for giving you this issue to take on when it's of poor quality.
